name: PROJECT K DEPLOY

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # Adjust to your project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i $ssh-private-key $EC2_USER@$EC2_HOST << 'EOF'
          cd /var/www/project/project_K
          git pull origin main
          source /var/www/project/venv/bin/activate
          python3 -m pip install -r requirements.txt
          python3 manage.py makemigration
          python3 manage.py migrate
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
