name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: |
          app_dir="/var/www/project/PROJECT-K"
          venv_dir="/var/www/project/venv"
          cd "$app_dir"
          
          # Pull the latest changes from the Git repository
          sudo git pull origin main
          
          # Check if the pull was successful
          if [ $? -eq 0 ]; then
            # Activate the virtual environment and run commands as the root user
            sudo bash -c "source $venv_dir/bin/activate && \
                          sudo python3 -m pip install --upgrade pip && \
                          sudo pip install -r requirements.txt && \
                          sudo python3 manage.py migrate && \
                          sudo systemctl restart gunicorn && \
                          sudo systemctl restart nginx"
            
            echo "Git pull successful, and service restarted."
          else
            echo "Git pull failed. Please check your Git repository."
          fi
