name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.x]

    env:
      RAZORPAY_KEY: rzp_live_Ue31MEqzdns5Zg
      RAZORPAY_SECRET: 2nou11r7oBApOctQdSGztzmv
      EMAIL_HOST_PASSWORD: pwgl msqz nebp pblx
      EMAIL_HOST_USER: astutelexservicado@gmail.com

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev pkg-config
        python -m venv env  # Create a virtual environment named 'env'
        source env/bin/activate  # Activate the virtual environment
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn
        pip install pdf2image
        pip install python-decouple

    - name: Copy static and media folders
      run: |
        sudo cp -r static /var/www/LexAi
        sudo cp -r media /var/www/LexAi

    - name: Serving Static Files
      run: |
        echo "Serving Static Files..."
        source env/bin/activate  # Ensure the virtual environment is activated
        python manage.py collectstatic --noinput

    - name: Running Database migration
      run: |
        echo "Running Database migration..."
        source ../venv/bin/activate  # Ensure the virtual environment is activated
        python manage.py makemigrations
        python manage.py migrate

    - name: Restart Gunicorn service
      run: |
        sudo systemctl restart Gunicorn
